'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { GlassPanel } from './GlassPanel';
import { ChromeButton } from './ChromeButton';

interface ReadmeGeneratorProps {
  username: string;
  stats: {
    totalRepos: number;
    totalStars: number;
    totalCommits: number;
    followers: number;
  };
  personality: {
    type: string;
    badge: string;
  };
}

export function ReadmeGenerator({ username, stats, personality }: ReadmeGeneratorProps) {
  const [copied, setCopied] = useState(false);

  const cardUrl = `${process.env.NEXT_PUBLIC_DOMAIN || 'https://gitwrapped.vercel.app'}/api/card?username=${username}`;

  const markdown = `
![GitWrapped](${cardUrl})

---

### 📊 My GitHub Stats

| Metric | Value |
|--------|-------|
| 📚 Repositories | ${stats.totalRepos} |
| ⭐ Total Stars | ${stats.totalStars} |
| 🎯 Total Commits | ${stats.totalCommits} |
| 👥 Followers | ${stats.followers} |

---

### 🏆 Achievements

- **Dev Type**: ${personality.type}
- **Badge**: ${personality.badge}

---
> Generated by [GitWrapped](https://gitwrapped.vercel.app) ✨
  `.trim();

  const copyToClipboard = async () => {
    await navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadImage = async () => {
    try {
      const response = await fetch(cardUrl);
      const svg = await response.text();
      const blob = new Blob([svg], { type: 'image/svg+xml' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `gitwrapped-${username}.svg`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Failed to download image:', error);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.6 }}
    >
      <GlassPanel glowColor="pink" className="p-8">
        <h3 className="font-orbitron text-2xl font-bold text-white mb-6">🧾 README Generator</h3>

        {/* Preview Card */}
        <div className="mb-6 p-4 bg-[rgba(0,0,0,0.3)] rounded-lg overflow-hidden">
          <img
            src={cardUrl}
            alt="GitWrapped Card"
            className="w-full max-w-md mx-auto rounded-lg"
          />
        </div>

        {/* Actions */}
        <div className="flex flex-wrap gap-4">
          <ChromeButton onClick={copyToClipboard} glowColor="cyan">
            {copied ? '✓ Copied!' : '📋 Copy Markdown'}
          </ChromeButton>
          <ChromeButton onClick={downloadImage} glowColor="magenta">
            💾 Download Image
          </ChromeButton>
        </div>

        {/* Markdown Preview */}
        <details className="mt-6">
          <summary className="font-mono text-sm text-gray-400 cursor-pointer hover:text-white">
            View Markdown Code
          </summary>
          <pre className="mt-4 p-4 bg-[rgba(0,0,0,0.5)] rounded-lg overflow-x-auto text-xs font-mono text-gray-300">
            {markdown}
          </pre>
        </details>
      </GlassPanel>
    </motion.div>
  );
}
